### ISSUE TITLE
Are there some publications about this project?

### ISSUE THREAD

**Issue by huhumeng** [Kyezil/iri_event_slam#1]
Thanks for your wonderful work, but it is confused with me that how to get the topic '/track/init_rendering'?

**Comment by louis-cl** [comment]
Hi, thanks for your interest! 
No, this specific work is not published. 

From what I remember 
/track/init_rendering is to get an initial position of the camera based on a known map.
For that purpose there's the track_init node that looks for a square and publish a rendering topic showing an image with the events and the detected square.
If you look at /track_init/launch/track_init.launch or
tracker/launch/track.launch
the rendering topic is remapped to /track/init_rendering. So if you run the track_init node manually or with the launch files you should obtain it.

Is that helpful?

**Comment by huhumeng** [comment]
Yes, i get it. The square detection result is for PnP pose estimation, thanks!
